### PR TITLE
Add initial support for app-web communication

### PR DESCRIPTION
**Pull request by hansemannn**
Example:
```js
var WK = require('ti.wkwebview');

var win = Ti.UI.createWindow({
    backgroundColor: "#fff",
    title: "WKWebView"
});

var nav = Ti.UI.iOS.createNavigationWindow({
    window: win
});
 
var webView = WK.createWebView({
     html: "<!DOCTYPE html><html><head><title>Local HTML</title></head><body><p style='font-size: 30px; color: red;'>Hello world!</p><script type=\"text/javascript\">WK.addEventListener('testEvent', function(e) { WK.fireEvent('testEventBack', {message: 'It worked!'}) })</script></body></html>"
});

var btn = Ti.UI.createButton({
    title: 'Post message'
});

btn.addEventListener('click', function() {
    WK.fireEvent('testEvent', {message: 'Titanium rocks!'});
});

WK.addEventListener('testEventBack', function(e) {
    alert(e.message);
});

win.setLeftNavButton(btn);
win.add(webView);
nav.open();
```

### CODE REVIEW

**Comment by AppsolutEinfach** [comment]
Ti.App-like events are a huge improvement!
The current API of `window.webkit.messageHandlers.Ti.postMessage()` is a little bit unusual for Ti.UI.WebView users.

**Comment by hansemannn** [comment]
@AppsolutEinfach That was not on purpose, I restored it just now. Please note it's not on the Ti.App namespace, since that will cause huge performance issues and global property binding. Keeping it local performs good in all tests so far. Try it out!

**Comment by hansemannn** [comment]
@eric34 Drafted 2.4.0 release [here](https://github.com/appcelerator-modules/Ti.WKWebView/releases/tag/v2.4.0).

**Comment by AppsolutEinfach** [comment]
We found some problem in
```
WK.addEventListener('testEventBack', function(e) {
   /* update UI */
});
```
when updating the user interface.

If in your `tiapp.xml` the `run-on-main-thread` property is unset or set to `false`
script errors and warnings (like `Creating [object TiUIView] in a different context than the calling function.`) occur.

**Workaround 1:**
add `<property name="run-on-main-thread" type="bool">true</property>` to `tiapp.xml` if you can

**Workaround 2:**
wrap your code in a `setTimeout()` call
```
WK.addEventListener('testEventBack', function(e) {
   setTimeout(function() {
       /* update UI */
   }, 0);
});
```

**Pull request merged**
