### PR TITLE
Update TiWkwebviewWebView.m

### PR DESCRIPTION
**Pull request by AppsolutEinfach**
adding property to disable zoom

### CODE REVIEW

**Comment by AppsolutEinfach** [comment]
invokes user script similar to `scalePageToFit`

**Comment by hansemannn** [comment]
I'd rather use [this delegate method](http://stackoverflow.com/a/31943976/5537752), looks more clean for this use-case.

**Comment by AppsolutEinfach** [comment]
Right, syntax is more clean. But there are valid concerns about future changes in internal class structure, see this [comment](http://stackoverflow.com/questions/25553711/disable-magnification-gesture-in-wkwebview/31943976#comment57862240_31943976).

**Comment by hansemannn** [comment]
Very good point, I can agree on that (knowing how crazy Apple can be with removing features silently). Can you add the property to the readme and bump the version to 2.2.0? thx!

**Comment by hansemannn** [comment]
Thanks @AppsolutEinfach, LGMT!

**Comment by hansemannn** [comment]
New release published: https://github.com/appcelerator-modules/Ti.WKWebView/releases/tag/v2.2.0

**Pull request merged**
